-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 23:12:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(225) NOT NULL,
  `name` VARCHAR(225) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `info` VARCHAR(225) NULL,
  `role` ENUM('admin', 'customer') NOT NULL,
  `status` ENUM('active', 'banned') NOT NULL,
  `subscribers` INT NULL,
  `subscription` INT NULL,
  `profilePhoto` VARCHAR(100) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(225) NULL,
  `date` DATE NOT NULL,
  `id_author` INT NOT NULL,
  `like_count` INT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_Post_User1_idx` (`id_author` ASC),
  CONSTRAINT `fk_Post_User1`
    FOREIGN KEY (`id_author`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(225) NULL,
  `date_time` DATETIME NOT NULL,
  `id_post` INT NOT NULL,
  `id_author` INT NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_Comment_Post1_idx` (`id_post` ASC),
  INDEX `fk_Comment_User1_idx` (`id_author` ASC),
  CONSTRAINT `fk_Comment_Post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `mydb`.`post` (`id_post`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`id_author`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hashtag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hashtag` (
  `id_hashtag` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_hashtag`),
  UNIQUE INDEX `text_UNIQUE` (`text` ASC),
  UNIQUE INDEX `idHashtag_UNIQUE` (`id_hashtag` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post_hashtag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post_hashtag` (
  `id_post_hashtag` INT NOT NULL AUTO_INCREMENT,
  `id_post` INT NOT NULL,
  `id_hashtag` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_post_hashtag`),
  INDEX `fk_post_hashtag_post1_idx` (`id_post` ASC),
  INDEX `fk_post_hashtag_hashtag1_idx` (`id_hashtag` ASC),
  CONSTRAINT `fk_post_hashtag_post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `mydb`.`post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_hashtag_hashtag1`
    FOREIGN KEY (`id_hashtag`)
    REFERENCES `mydb`.`hashtag` (`id_hashtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`like` (
  `id_like` INT NOT NULL AUTO_INCREMENT,
  `id_post` INT NOT NULL,
  `id_user` INT NOT NULL,
  INDEX `fk_Like_Post1_idx` (`id_post` ASC),
  INDEX `fk_Like_User1_idx` (`id_user` ASC),
  PRIMARY KEY (`id_like`),
  CONSTRAINT `fk_Like_Post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `mydb`.`post` (`id_post`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Like_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `id_direct` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(150) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `id_receiver` INT NOT NULL,
  `id_sender` INT NOT NULL,
  INDEX `fk_Direct_User1_idx` (`id_sender` ASC),
  PRIMARY KEY (`id_direct`),
  CONSTRAINT `fkDirectUser`
    FOREIGN KEY (`id_receiver`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direct_User1`
    FOREIGN KEY (`id_sender`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`photo` (
  `id_photo` INT NOT NULL AUTO_INCREMENT,
  `photo_path` VARCHAR(100) NOT NULL,
  `id_post` INT NOT NULL,
  PRIMARY KEY (`id_photo`),
  INDEX `fk_photo_post1_idx` (`id_post` ASC),
  CONSTRAINT `fk_photo_post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `mydb`.`post` (`id_post`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sub` (
  `id_sub` INT NOT NULL AUTO_INCREMENT,
  `id_subcriber` INT NOT NULL,
  `id_host` INT NOT NULL,
  INDEX `fk_sub_user1_idx` (`id_subcriber` ASC),
  INDEX `fk_sub_user2_idx` (`id_host` ASC),
  PRIMARY KEY (`id_sub`),
  CONSTRAINT `fk_sub_user1`
    FOREIGN KEY (`id_subcriber`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sub_user2`
    FOREIGN KEY (`id_host`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
